version: 2

models:
  - name: fct_order_items
    columns:
      - name: order_item_id
        tests:
          - unique
          - not_null

  - name: fct_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
